<?php

namespace App\DataFixtures;

use App\Entity\Marque;
use App\Entity\Telephone;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class TelephoneFixtures extends Fixture implements DependentFixtureInterface
{
    public function getDependencies(): array
    {
        return [MarqueFixtures::class];
    }

    public function load(ObjectManager $manager): void
    {
        $telephones = [
            'Apple' => [
                ['model' => 'iPhone 14 Pro Max', 'image' => 'iphone_14_pro_max.webp'],
                ['model' => 'iPhone 14 Pro', 'image' => 'iphone_14_pro.webp'],
                ['model' => 'iPhone 14 Plus', 'image' => 'iphone_14_plus.webp'],
                ['model' => 'iPhone 14', 'image' => 'iphone_14.webp'],
                ['model' => 'iPhone 13 Pro Max', 'image' => 'iphone_13_pro_max.webp'],
                ['model' => 'iPhone 13 Pro', 'image' => 'iphone_13_pro.webp'],
                ['model' => 'iPhone 13', 'image' => 'iphone_13.webp'],
                ['model' => 'iPhone Se (2022)', 'image' => 'iphone_se_2022.webp'],
                ['model' => 'iPhone 13 Mini', 'image' => 'iphone_13_mini.webp'],
                ['model' => 'iPhone 12 Pro Max', 'image' => 'iphone_12_pro_max.webp'],
                ['model' => 'iPhone 12 Pro', 'image' => 'iphone_12_pro.webp'],
                ['model' => 'iPhone 12', 'image' => 'iphone_12.webp'],
                ['model' => 'iPhone 12 Mini', 'image' => 'iphone_12_mini.webp'],
                ['model' => 'iPhone 11 Pro Max', 'image' => 'iphone_11_pro_max.webp'],
                ['model' => 'iPhone 11 Pro', 'image' => 'iphone_11_pro.webp'],
                ['model' => 'iPhone 11', 'image' => 'iphone_11.webp'],
                ['model' => 'iPhone Xs Max', 'image' => 'iphone_xs_max.webp'],
                ['model' => 'iPhone Xs', 'image' => 'iphone_xs.webp'],
                ['model' => 'iPhone Xr', 'image' => 'iphone_xr.webp'],
                ['model' => 'iPhone X', 'image' => 'iphone_x.webp'],
                ['model' => 'iPhone Se (2020)', 'image' => 'iphone_se_2020.webp'],
                ['model' => 'iPhone Se', 'image' => 'iphone_se.webp'],
                ['model' => 'iPhone 8 Plus', 'image' => 'iphone_8_plus.webp'],
                ['model' => 'iPhone 8', 'image' => 'iphone_8.webp'],
                ['model' => 'iPhone 7 Plus', 'image' => 'iphone_7_plus.webp'],
                ['model' => 'iPhone 7', 'image' => 'iphone_7.webp'],
                ['model' => 'iPhone 6S Plus', 'image' => 'iphone_6s_plus.webp'],
                ['model' => 'iPhone 6S', 'image' => 'iphone_6s.webp'],
                ['model' => 'iPhone 6 Plus', 'image' => 'iphone_6_plus.webp'],
                ['model' => 'iPhone 6', 'image' => 'iphone_6.webp'],
                ['model' => 'iPhone 5S', 'image' => 'iphone_5s.webp'],
                ['model' => 'iPhone 5C', 'image' => 'iphone_5c.webp'],
                ['model' => 'iPhone 5', 'image' => 'iphone_5.webp'],
            ],
            'Samsung' => [
                ['model' => 'Galaxy S23 Ultra', 'image' => 'galaxy_s23_ultra.webp'],
                ['model' => 'Galaxy S23+', 'image' => 'galaxy_s23_plus.webp'],
                ['model' => 'Galaxy S23', 'image' => 'galaxy_s23.webp'],
                ['model' => 'Galaxy S22 Ultra', 'image' => 'galaxy_s22_ultra.webp'],
                ['model' => 'Galaxy S22+', 'image' => 'galaxy_s22_plus.webp'],
                ['model' => 'Galaxy S22', 'image' => 'galaxy_s22.webp'],
                ['model' => 'Galaxy S21 FE 5G', 'image' => 'galaxy_s21_fe_5g.webp'],
                ['model' => 'Galaxy S21 Ultra 5G', 'image' => 'galaxy_s21_ultra_5g.webp'],
                ['model' => 'Galaxy S21+ 5G', 'image' => 'galaxy_s21_plus_5g.webp'],
                ['model' => 'Galaxy S21 5G', 'image' => 'galaxy_s21_5g.webp'],
                ['model' => 'Galaxy S20 Ultra 5G', 'image' => 'galaxy_s20_ultra_5g.webp'],
                ['model' => 'Galaxy S20+ 5G', 'image' => 'galaxy_s20_plus_5g.webp'],
                ['model' => 'Galaxy S20+', 'image' => 'galaxy_s20_plus.webp'],
                ['model' => 'Galaxy S20 Fe 5G', 'image' => 'galaxy_s20_fe_5g.webp'],
                ['model' => 'Galaxy S20 Fe', 'image' => 'galaxy_s20_fe.webp'],
                ['model' => 'Galaxy S20 5G', 'image' => 'galaxy_s20_5g.webp'],
                ['model' => 'Galaxy S20', 'image' => 'galaxy_s20.webp'],
                ['model' => 'Galaxy S10+', 'image' => 'galaxy_s10_plus.webp'],
                ['model' => 'Galaxy S10 5G', 'image' => 'galaxy_s10_5g.webp'],
                ['model' => 'Galaxy S10', 'image' => 'galaxy_s10.webp'],
                ['model' => 'Galaxy S10 Lite', 'image' => 'galaxy_s10_lite.webp'],
                ['model' => 'Galaxy S10E', 'image' => 'galaxy_s10e.webp'],
                ['model' => 'Galaxy S9+', 'image' => 'galaxy_s9_plus.webp'],
                ['model' => 'Galaxy S9', 'image' => 'galaxy_s9.webp'],
                ['model' => 'Galaxy S8 Plus', 'image' => 'galaxy_s8_plus.webp'],
                ['model' => 'Galaxy S8', 'image' => 'galaxy_s8.webp'],
                ['model' => 'Galaxy S7 Edge', 'image' => 'galaxy_s7_edge.webp'],
                ['model' => 'Galaxy S7', 'image' => 'galaxy_s7.webp'],
                ['model' => 'Galaxy S6 Edge Plus', 'image' => 'galaxy_s6_edge_plus.webp'],
                ['model' => 'Galaxy S6 Edge', 'image' => 'galaxy_s6_edge.webp'],
                ['model' => 'Galaxy S6', 'image' => 'galaxy_s6.webp'],
                ['model' => 'Galaxy A53 5G', 'image' => 'galaxy_a53_5g.webp'],
                ['model' => 'Galaxy A33 5G', 'image' => 'galaxy_a33_5g.webp'],
                ['model' => 'Galaxy A23 5G', 'image' => 'galaxy_a23_5g.webp'],
                ['model' => 'Galaxy A23', 'image' => 'galaxy_a23.webp'],
                ['model' => 'Galaxy A13 5G', 'image' => 'galaxy_a13_5g.webp'],
                ['model' => 'Galaxy A13', 'image' => 'galaxy_a13.webp'],
                ['model' => 'Galaxy A04S', 'image' => 'galaxy_a04s.webp'],
                ['model' => 'Galaxy A03S', 'image' => 'galaxy_a03s.webp'],
                ['model' => 'Galaxy A03', 'image' => 'galaxy_a03.webp'],
                ['model' => 'Galaxy A72', 'image' => 'galaxy_a72.webp'],
                ['model' => 'Galaxy A52S 5G', 'image' => 'galaxy_a52s_5g.webp'],
                ['model' => 'Galaxy A52 5G', 'image' => 'galaxy_a52_5g.webp'],
                ['model' => 'Galaxy A52', 'image' => 'galaxy_a52.webp'],
                ['model' => 'Galaxy A42 5G', 'image' => 'galaxy_a42_5g.webp'],
                ['model' => 'Galaxy A32 5G', 'image' => 'galaxy_a32_5g.webp'],
                ['model' => 'Galaxy A32', 'image' => 'galaxy_a32.webp'],
                ['model' => 'Galaxy A22 5G', 'image' => 'galaxy_a22_5g.webp'],
                ['model' => 'Galaxy A12', 'image' => 'galaxy_a12.webp'],
                ['model' => 'Galaxy A02S', 'image' => 'galaxy_a02s.webp'],
                ['model' => 'Galaxy A71', 'image' => 'galaxy_a71.webp'],
                ['model' => 'Galaxy A51 5G', 'image' => 'galaxy_a51_5g.webp'],
                ['model' => 'Galaxy A51', 'image' => 'galaxy_a51.webp'],
                ['model' => 'Galaxy A41', 'image' => 'galaxy_a41.webp'],
                ['model' => 'Galaxy A31', 'image' => 'galaxy_a31.webp'],
                ['model' => 'Galaxy A21S', 'image' => 'galaxy_a21s.webp'],
                ['model' => 'Galaxy A80', 'image' => 'galaxy_a80.webp'],
                ['model' => 'Galaxy A70', 'image' => 'galaxy_a70.webp'],
                ['model' => 'Galaxy A50', 'image' => 'galaxy_a50.webp'],
                ['model' => 'Galaxy A40', 'image' => 'galaxy_a40.webp'],
                ['model' => 'Galaxy A30S', 'image' => 'galaxy_a30s.webp'],
                ['model' => 'Galaxy A20S', 'image' => 'galaxy_a20s.webp'],
                ['model' => 'Galaxy A20E', 'image' => 'galaxy_a20e.webp'],
                ['model' => 'Galaxy A20', 'image' => 'galaxy_a20.webp'],
                ['model' => 'Galaxy A10S', 'image' => 'galaxy_a10s.webp'],
                ['model' => 'Galaxy A10', 'image' => 'galaxy_a10.webp'],
                ['model' => 'Galaxy A9 (2018)', 'image' => 'galaxy_a9_2018.webp'],
                ['model' => 'Galaxy A8 (2018)', 'image' => 'galaxy_a8_2018.webp'],
                ['model' => 'Galaxy A7 (2018)', 'image' => 'galaxy_a7_2018.webp'],
                ['model' => 'Galaxy A6 (2018)', 'image' => 'galaxy_a6_2018.webp'],
                ['model' => 'Galaxy A5 (2017)', 'image' => 'galaxy_a5_2017.webp'],
                ['model' => 'Galaxy A3 (2017)', 'image' => 'galaxy_a3_2017.webp'],
                ['model' => 'Galaxy A5 (2016)', 'image' => 'galaxy_a5_2016.webp'],
                ['model' => 'Galaxy A3 (2016)', 'image' => 'galaxy_a3_2016.webp'],
                ['model' => 'Galaxy A7', 'image' => 'galaxy_a7.webp'],
                ['model' => 'Galaxy A5', 'image' => 'galaxy_a5.webp'],
                ['model' => 'Galaxy A3', 'image' => 'galaxy_a3.webp'],
                ['model' => 'Galaxy Z Fold4', 'image' => 'galaxy_z_fold4.webp'],
                ['model' => 'Galaxy Z Fold3', 'image' => 'galaxy_z_fold3.webp'],
                ['model' => 'Galaxy Z Flip4', 'image' => 'galaxy_z_flip4.webp'],
                ['model' => 'Galaxy Z Flip3 5G', 'image' => 'galaxy_z_flip3_5g.webp'],
                ['model' => 'Galaxy Z Fold2', 'image' => 'galaxy_z_fold2.webp'],
                ['model' => 'Galaxy Z Flip', 'image' => 'galaxy_z_flip.webp'],
                ['model' => 'Galaxy Fold 5G', 'image' => 'galaxy_fold_5g.webp'],
                ['model' => 'Galaxy Fold', 'image' => 'galaxy_fold.webp'],
                ['model' => 'Galaxy Note 20 Ultra 5G', 'image' => 'galaxy_note_20_ultra_5g.webp'],
                ['model' => 'Galaxy Note 20 5G', 'image' => 'galaxy_note_20_5g.webp'],
                ['model' => 'Galaxy Note 20', 'image' => 'galaxy_note_20.webp'],
                ['model' => 'Galaxy Note 10+', 'image' => 'galaxy_note_10_plus.webp'],
                ['model' => 'Galaxy Note 10', 'image' => 'galaxy_note_10.webp'],
                ['model' => 'Galaxy Note10 Lite', 'image' => 'galaxy_note10_lite.webp'],
                ['model' => 'Galaxy Note 9', 'image' => 'galaxy_note_9.webp'],
                ['model' => 'Galaxy Note 8', 'image' => 'galaxy_note_8.webp'],
                ['model' => 'Galaxy M53 5G', 'image' => 'galaxy_m53_5g.webp'],
                ['model' => 'Galaxy M33 5G', 'image' => 'galaxy_m33_5g.webp'],
                ['model' => 'Galaxy M23 5G', 'image' => 'galaxy_m23_5g.webp'],
                ['model' => 'Galaxy M32', 'image' => 'galaxy_m32.webp'],
                ['model' => 'Galaxy M12', 'image' => 'galaxy_m12.webp'],
                ['model' => 'Galaxy M51', 'image' => 'galaxy_m51.webp'],
                ['model' => 'Galaxy M31', 'image' => 'galaxy_m31.webp'],
                ['model' => 'Galaxy M11', 'image' => 'galaxy_m11.webp'],
                ['model' => 'Galaxy J8', 'image' => 'galaxy_j8.webp'],
                ['model' => 'Galaxy J6 Plus', 'image' => 'galaxy_j6_plus.webp'],
                ['model' => 'Galaxy J6 (2018)', 'image' => 'galaxy_j6_2018.webp'],
                ['model' => 'Galaxy J4 Plus', 'image' => 'galaxy_j4_plus.webp'],
                ['model' => 'Galaxy J4', 'image' => 'galaxy_j4.webp'],
                ['model' => 'Galaxy J5 (2017)', 'image' => 'galaxy_j5_2017.webp'],
                ['model' => 'Galaxy J3 (2017)', 'image' => 'galaxy_j3_2017.webp'],
                ['model' => 'Galaxy J7 (2016)', 'image' => 'galaxy_j7_2016.webp'],
                ['model' => 'Galaxy J3 (2016)', 'image' => 'galaxy_j3_2016.webp'],
                ['model' => 'Galaxy J5', 'image' => 'galaxy_j5.webp'],
                ['model' => 'Galaxy Xcover5', 'image' => 'galaxy_xcover5.webp'],
            ],
            'Xiaomi' => [
                ['model' => '11T Pro', 'image' => '11t_pro.webp'],
                ['model' => '11 Lite 5G Ne', 'image' => '11_lite_5g_ne.webp'],
                ['model' => 'Mi 10', 'image' => 'mi_10.webp'],
                ['model' => 'Mi 10 Lite', 'image' => 'mi_10_lite.webp'],
                ['model' => 'Mi 10 Lite 5G', 'image' => 'mi_10_lite_5g.webp'],
                ['model' => 'Mi 10 Pro', 'image' => 'mi_10_pro.webp'],
                ['model' => 'Mi 10T', 'image' => 'mi_10t.webp'],
                ['model' => 'Mi 10T Lite', 'image' => 'mi_10t_lite.webp'],
                ['model' => 'Mi 10T Pro', 'image' => 'mi_10t_pro.webp'],
                ['model' => 'Mi 11', 'image' => 'mi_11.webp'],
                ['model' => 'Mi 11 Lite', 'image' => 'mi_11_lite.webp'],
                ['model' => 'Mi 11 Lite 5G', 'image' => 'mi_11_lite_5g.webp'],
                ['model' => 'Mi 11 Ultra', 'image' => 'mi_11_ultra.webp'],
                ['model' => 'Mi 11I', 'image' => 'mi_11i.webp'],
                ['model' => 'Mi 5', 'image' => 'mi_5.webp'],
                ['model' => 'Mi 5S', 'image' => 'mi_5s.webp'],
                ['model' => 'Mi 6', 'image' => 'mi_6.webp'],
                ['model' => 'Mi 8', 'image' => 'mi_8.webp'],
                ['model' => 'Mi 8 Lite', 'image' => 'mi_8_lite.webp'],
                ['model' => 'Mi 8 Pro', 'image' => 'mi_8_pro.webp'],
                ['model' => 'Mi 9', 'image' => 'mi_9.webp'],
                ['model' => 'Mi 9 Lite', 'image' => 'mi_9_lite.webp'],
                ['model' => 'Mi 9 Se', 'image' => 'mi_9_se.webp'],
                ['model' => 'Mi 9T', 'image' => 'mi_9t.webp'],
                ['model' => 'Mi 9T Pro', 'image' => 'mi_9t_pro.webp'],
                ['model' => 'Mi A1', 'image' => 'mi_a1.webp'],
                ['model' => 'Mi A2', 'image' => 'mi_a2.webp'],
                ['model' => 'Mi A2 Lite', 'image' => 'mi_a2_lite.webp'],
                ['model' => 'Mi A3', 'image' => 'mi_a3.webp'],
                ['model' => 'Mi Max', 'image' => 'mi_max.webp'],
                ['model' => 'Mi Max 2', 'image' => 'mi_max_2.webp'],
                ['model' => 'Mi Max 3', 'image' => 'mi_max_3.webp'],
                ['model' => 'Mi Mix', 'image' => 'mi_mix.webp'],
                ['model' => 'Mi Mix 2', 'image' => 'mi_mix_2.webp'],
                ['model' => 'Mi Mix 2S', 'image' => 'mi_mix_2s.webp'],
                ['model' => 'Mi Mix 3', 'image' => 'mi_mix_3.webp'],
                ['model' => 'Mi Mix 3 5G', 'image' => 'mi_mix_3_5g.webp'],
                ['model' => 'Mi Note 10', 'image' => 'mi_note_10.webp'],
                ['model' => 'Mi Note 10 Lite', 'image' => 'mi_note_10_lite.webp'],
                ['model' => 'Mi Note 10 Pro', 'image' => 'mi_note_10_pro.webp'],
                ['model' => 'Mi Note 2', 'image' => 'mi_note_2.webp'],
                ['model' => 'Mi Note 3', 'image' => 'mi_note_3.webp'],
                ['model' => 'Mi Play', 'image' => 'mi_play.webp'],
                ['model' => 'Mix 2', 'image' => 'mix_2.webp'],
                ['model' => 'Note 7', 'image' => 'note_7.webp'],
                ['model' => 'Poco F1', 'image' => 'poco_f1.webp'],
                ['model' => 'Poco F2 Pro', 'image' => 'poco_f2_pro.webp'],
                ['model' => 'Poco F3', 'image' => 'poco_f3.webp'],
                ['model' => 'Poco M3', 'image' => 'poco_m3.webp'],
                ['model' => 'Poco M3 Pro', 'image' => 'poco_m3_pro.webp'],
                ['model' => 'Poco X3 Nfc', 'image' => 'poco_x3_nfc.webp'],
                ['model' => 'Poco X3 Pro', 'image' => 'poco_x3_pro.webp'],
                ['model' => 'Pocophone F1', 'image' => 'pocophone_f1.webp'],
                ['model' => 'Redmi 3', 'image' => 'redmi_3.webp'],
                ['model' => 'Redmi 3S', 'image' => 'redmi_3s.webp'],
                ['model' => 'Redmi 4', 'image' => 'redmi_4.webp'],
                ['model' => 'Redmi 4A', 'image' => 'redmi_4a.webp'],
                ['model' => 'Redmi 4X', 'image' => 'redmi_4x.webp'],
                ['model' => 'Redmi 5', 'image' => 'redmi_5.webp'],
                ['model' => 'Redmi 5 Plus', 'image' => 'redmi_5_plus.webp'],
                ['model' => 'Redmi 5A', 'image' => 'redmi_5a.webp'],
                ['model' => 'Redmi 6', 'image' => 'redmi_6.webp'],
                ['model' => 'Redmi 6A', 'image' => 'redmi_6a.webp'],
                ['model' => 'Redmi 7', 'image' => 'redmi_7.webp'],
                ['model' => 'Redmi 7A', 'image' => 'redmi_7a.webp'],
                ['model' => 'Redmi 8', 'image' => 'redmi_8.webp'],
                ['model' => 'Redmi 8A', 'image' => 'redmi_8a.webp'],
                ['model' => 'Redmi 9', 'image' => 'redmi_9.webp'],
                ['model' => 'Redmi 9A', 'image' => 'redmi_9a.webp'],
                ['model' => 'Redmi 9At', 'image' => 'redmi_9at.webp'],
                ['model' => 'Redmi 9C', 'image' => 'redmi_9c.webp'],
                ['model' => 'Redmi 9T', 'image' => 'redmi_9t.webp'],
                ['model' => 'Redmi Go', 'image' => 'redmi_go.webp'],
                ['model' => 'Redmi Note 10', 'image' => 'redmi_note_10.webp'],
                ['model' => 'Redmi Note 10 Pro', 'image' => 'redmi_note_10_pro.webp'],
                ['model' => 'Redmi Note 10S', 'image' => 'redmi_note_10s.webp'],
                ['model' => 'Redmi Note 3', 'image' => 'redmi_note_3.webp'],
                ['model' => 'Redmi Note 3 Prime', 'image' => 'redmi_note_3_prime.webp'],
                ['model' => 'Redmi Note 3 Pro', 'image' => 'redmi_note_3_pro.webp'],
                ['model' => 'Redmi Note 4', 'image' => 'redmi_note_4.webp'],
                ['model' => 'Redmi Note 4X', 'image' => 'redmi_note_4x.webp'],
                ['model' => 'Redmi Note 5', 'image' => 'redmi_note_5.webp'],
                ['model' => 'Redmi Note 5A', 'image' => 'redmi_note_5a.webp'],
                ['model' => 'Redmi Note 5A Prime', 'image' => 'redmi_note_5a_prime.webp'],
                ['model' => 'Redmi Note 6 Pro', 'image' => 'redmi_note_6_pro.webp'],
                ['model' => 'Redmi Note 8', 'image' => 'redmi_note_8.webp'],
                ['model' => 'Redmi Note 8 Pro', 'image' => 'redmi_note_8_pro.webp'],
                ['model' => 'Redmi Note 8T', 'image' => 'redmi_note_8t.webp'],
                ['model' => 'Redmi Note 9', 'image' => 'redmi_note_9.webp'],
                ['model' => 'Redmi Note 9 Nfc', 'image' => 'redmi_note_9_nfc.webp'],
                ['model' => 'Redmi Note 9 Pro', 'image' => 'redmi_note_9_pro.webp'],
                ['model' => 'Redmi Note 9S', 'image' => 'redmi_note_9s.webp'],
                ['model' => 'Redmi Note 9T', 'image' => 'redmi_note_9t.webp'],
                ['model' => 'Redmi S2', 'image' => 'redmi_s2.webp'],
                ['model' => 'Xiaomi Mix 3 5G', 'image' => 'xiaomi_mix_3_5g.webp'],
            ],
            'Huawei' => [
                ['model' => 'P40 Pro', 'image' => 'p40_pro.webp'],
                ['model' => 'P40', 'image' => 'p40.webp'],
                ['model' => 'P40 Lite E', 'image' => 'p40_lite_e.webp'],
                ['model' => 'P40 Lite 5G', 'image' => 'p40_lite_5g.webp'],
                ['model' => 'P40 Lite', 'image' => 'p40_lite.webp'],
                ['model' => 'P30 Pro', 'image' => 'p30_pro.webp'],
                ['model' => 'Mate 40 Pro', 'image' => 'mate_40_pro.webp'],
                ['model' => 'P30', 'image' => 'p30.webp'],
                ['model' => 'P30 Lite', 'image' => 'p30_lite.webp'],
                ['model' => 'Mate 30 Pro', 'image' => 'mate_30_pro.webp'],
                ['model' => 'P20 Pro', 'image' => 'p20_pro.webp'],
                ['model' => 'P20', 'image' => 'p20.webp'],
                ['model' => 'P20 Lite', 'image' => 'p20_lite.webp'],
                ['model' => 'Mate 20 Pro', 'image' => 'mate_20_pro.webp'],
                ['model' => 'Mate 20', 'image' => 'mate_20.webp'],
                ['model' => 'Mate 20 X', 'image' => 'mate_20_x.webp'],
                ['model' => 'Mate 20 Lite', 'image' => 'mate_20_lite.webp'],
                ['model' => 'P Smart 2021', 'image' => 'p_smart_2021.webp'],
                ['model' => 'P Smart 2020', 'image' => 'p_smart_2020.webp'],
                ['model' => 'P Smart 2019', 'image' => 'p_smart_2019.webp'],
                ['model' => 'P Smart+ 2019', 'image' => 'p_smart_plus_2019.webp'],
                ['model' => 'P Smart Z', 'image' => 'p_smart_z.webp'],
                ['model' => 'P Smart S', 'image' => 'p_smart_s.webp'],
                ['model' => 'P Smart+', 'image' => 'p_smart_plus.webp'],
                ['model' => 'P Smart', 'image' => 'p_smart.webp'],
                ['model' => 'Nova 5T', 'image' => 'nova_5t.webp'],
                ['model' => 'P10 Plus', 'image' => 'p10_plus.webp'],
                ['model' => 'P10', 'image' => 'p10.webp'],
                ['model' => 'P10 Lite', 'image' => 'p10_lite.webp'],
                ['model' => 'Mate 10 Pro', 'image' => 'mate_10_pro.webp'],
                ['model' => 'Mate 10 Lite', 'image' => 'mate_10_lite.webp'],
                ['model' => 'P9 Plus', 'image' => 'p9_plus.webp'],
                ['model' => 'P9', 'image' => 'p9.webp'],
                ['model' => 'P9 Lite', 'image' => 'p9_lite.webp'],
                ['model' => 'Mate 9 Pro', 'image' => 'mate_9_pro.webp'],
                ['model' => 'Mate 9', 'image' => 'mate_9.webp'],
                ['model' => 'P8', 'image' => 'p8.webp'],
                ['model' => 'P8 Lite', 'image' => 'p8_lite.webp'],
                ['model' => 'P8 Lite 2017', 'image' => 'p8_lite_2017.webp'],
                ['model' => 'Mate 8', 'image' => 'mate_8.webp'],
                ['model' => 'Nova 2', 'image' => 'nova_2.webp'],
                ['model' => 'Nova Plus', 'image' => 'nova_plus.webp'],
                ['model' => 'Nova', 'image' => 'nova.webp'],
                ['model' => 'Y6S', 'image' => 'y6s.webp'],
                ['model' => 'Y6P', 'image' => 'y6p.webp'],
                ['model' => 'Y6 2019', 'image' => 'y6_2019.webp'],
                ['model' => 'Y6 2018', 'image' => 'y6_2018.webp'],
                ['model' => 'Y6 2017', 'image' => 'y6_2017.webp'],
                ['model' => 'Y6 Pro 2017', 'image' => 'y6_pro_2017.webp'],
                ['model' => 'Y5P', 'image' => 'y5p.webp'],
                ['model' => 'Y5 (2019)', 'image' => 'y5_2019.webp'],
                ['model' => 'Y5 (2018)', 'image' => 'y5_2018.webp'],
                ['model' => 'Y6 Pro', 'image' => 'y6_pro.webp'],
                ['model' => 'Y6', 'image' => 'y6.webp'],
                ['model' => 'Y6 Ii Compact', 'image' => 'y6_ii_compact.webp'],
                ['model' => 'Y625', 'image' => 'y625.webp'],
                ['model' => 'Y6Ii', 'image' => 'y6ii.webp'],
                ['model' => 'Y7 Prime 2019', 'image' => 'y7_prime_2019.webp'],
                ['model' => 'Y7 Prime 2018', 'image' => 'y7_prime_2018.webp'],
                ['model' => 'Y7 Prime', 'image' => 'y7_prime.webp'],
                ['model' => 'Y7', 'image' => 'y7.webp'],
                ['model' => 'Ascend Y530', 'image' => 'ascend_y530.webp'],
                ['model' => 'Mate S', 'image' => 'mate_s.webp'],
                ['model' => 'Nexus 6P', 'image' => 'nexus_6p.webp'],
                ['model' => 'G Play Mini', 'image' => 'g_play_mini.webp'],
            ],
            'Honor' => [
                ['model' => 'Honor 10', 'image' => 'honor_10.webp'],
                ['model' => 'Honor 10 Lite', 'image' => 'honor_10_lite.webp'],
                ['model' => 'Honor 20 Lite', 'image' => 'honor_20_lite.webp'],
                ['model' => 'Honor 20 Pro', 'image' => 'honor_20_pro.webp'],
                ['model' => 'Honor 8', 'image' => 'honor_8.webp'],
                ['model' => 'Honor 8 Lite', 'image' => 'honor_8_lite.webp'],
                ['model' => 'Honor 8 Pro', 'image' => 'honor_8_pro.webp'],
                ['model' => 'Honor 8A', 'image' => 'honor_8a.webp'],
                ['model' => 'Honor 8X', 'image' => 'honor_8x.webp'],
                ['model' => 'Honor 9', 'image' => 'honor_9.webp'],
                ['model' => 'Honor 9 Lite', 'image' => 'honor_9_lite.webp'],
                ['model' => 'Honor 9X', 'image' => 'honor_9x.webp'],
                ['model' => 'Honor 9X Lite', 'image' => 'honor_9x_lite.webp'],
                ['model' => 'Honor Play', 'image' => 'honor_play.webp'],
                ['model' => 'Honor V10', 'image' => 'honor_v10.webp'],
                ['model' => 'Honor View 20', 'image' => 'honor_view_20.webp'],
            ],
            'Oppo' => [
                ['model' => 'Find X3 Neo', 'image' => 'find_x3_neo.webp'],
                ['model' => 'Find X3 Lite', 'image' => 'find_x3_lite.webp'],
                ['model' => 'Find X2 Pro', 'image' => 'find_x2_pro.webp'],
                ['model' => 'Find X2 Neo', 'image' => 'find_x2_neo.webp'],
                ['model' => 'Find X2 Lite', 'image' => 'find_x2_lite.webp'],
                ['model' => 'Reno6 5G', 'image' => 'reno6_5g.webp'],
                ['model' => 'Reno4 Pro 5G', 'image' => 'reno4_pro_5g.webp'],
                ['model' => 'Reno4 Pro', 'image' => 'reno4_pro.webp'],
                ['model' => 'Reno4 5G', 'image' => 'reno4_5g.webp'],
                ['model' => 'Reno2', 'image' => 'reno2.webp'],
                ['model' => 'Reno', 'image' => 'reno.webp'],
                ['model' => 'A94', 'image' => 'a94.webp'],
                ['model' => 'A54 5G', 'image' => 'a54_5g.webp'],
                ['model' => 'A9 (2020)', 'image' => 'a9_2020.webp'],
                ['model' => 'A53S', 'image' => 'a53s.webp'],
                ['model' => 'A74 5G', 'image' => 'a74_5g.webp'],
                ['model' => 'A72', 'image' => 'a72.webp'],
                ['model' => 'A16s', 'image' => 'a16s.webp'],
                ['model' => 'A15S', 'image' => 'a15s.webp'],
                ['model' => 'A15', 'image' => 'a15.webp'],
            ],
            'Sony' => [
                ['model' => 'Xperia 1 II', 'image' => 'xperia_1_ii.webp'],
                ['model' => 'Xperia 10 Plus', 'image' => 'xperia_10_plus.webp'],
                ['model' => 'Xperia 5 II', 'image' => 'xperia_5_ii.webp'],
                ['model' => 'Xperia 5', 'image' => 'xperia_5.webp'],
                ['model' => 'Xperia Xz3', 'image' => 'xperia_xz3.webp'],
                ['model' => 'Xperia Xz2 Compact', 'image' => 'xperia_xz2_compact.webp'],
                ['model' => 'Xperia Xz1', 'image' => 'xperia_xz1.webp'],
                ['model' => 'Xperia Xa1', 'image' => 'xperia_xa1.webp'],
                ['model' => 'Xperia C5 Ultra', 'image' => 'xperia_c5_ultra.webp'],
                ['model' => 'Xperia E3', 'image' => 'xperia_e3.webp'],
                ['model' => 'Xperia M2', 'image' => 'xperia_m2.webp'],
                ['model' => 'Xperia M4 Aqua', 'image' => 'xperia_m4_aqua.webp'],
                ['model' => 'Xperia M5', 'image' => 'xperia_m5.webp'],
                ['model' => 'Xperia T3', 'image' => 'xperia_t3.webp'],
                ['model' => 'Xperia X', 'image' => 'xperia_x.webp'],
                ['model' => 'Xperia Xa', 'image' => 'xperia_xa.webp'],
                ['model' => 'Xperia Xa Ultra', 'image' => 'xperia_xa_ultra.webp'],
                ['model' => 'Xperia Xz', 'image' => 'xperia_xz.webp'],
                ['model' => 'Xperia Z', 'image' => 'xperia_z.webp'],
                ['model' => 'Xperia Z1', 'image' => 'xperia_z1.webp'],
                ['model' => 'Xperia Z1 Compact', 'image' => 'xperia_z1_compact.webp'],
                ['model' => 'Xperia Z2', 'image' => 'xperia_z2.webp'],
                ['model' => 'Xperia Z3', 'image' => 'xperia_z3.webp'],
                ['model' => 'Xperia Z3 Compact', 'image' => 'xperia_z3_compact.webp'],
                ['model' => 'Xperia Z5', 'image' => 'xperia_z5.webp'],
                ['model' => 'Xperia Z5 Compact', 'image' => 'xperia_z5_compact.webp'],
                ['model' => 'Xperia Z5 Dual', 'image' => 'xperia_z5_dual.webp'],
                ['model' => 'Xperia Z5 Premium', 'image' => 'xperia_z5_premium.webp'],
            ],
            'Asus' => [
                ['model' => 'Zenfone Max (M2)', 'image' => 'zenfone_max_m2.webp'],
                ['model' => 'Zenfone Max Pro (M2)', 'image' => 'zenfone_max_pro_m2.webp'],
            ],
            'Nokia' => [
                ['model' => '7.1', 'image' => 'nokia_7_1.webp'],
                ['model' => '3', 'image' => 'nokia_3.webp'],
                ['model' => '9 Pureview', 'image' => 'nokia_9_pureview.webp'],
                ['model' => 'Lumia 1020', 'image' => 'lumia_1020.webp'],
                ['model' => 'Lumia 1520', 'image' => 'lumia_1520.webp'],
                ['model' => 'Lumia 520', 'image' => 'lumia_520.webp'],
                ['model' => 'Lumia 530', 'image' => 'lumia_530.webp'],
                ['model' => 'Lumia 535', 'image' => 'lumia_535.webp'],
                ['model' => 'Lumia 610', 'image' => 'lumia_610.webp'],
                ['model' => 'Lumia 620', 'image' => 'lumia_620.webp'],
                ['model' => 'Lumia 625', 'image' => 'lumia_625.webp'],
                ['model' => 'Lumia 630', 'image' => 'lumia_630.webp'],
                ['model' => 'Lumia 635', 'image' => 'lumia_635.webp'],
                ['model' => 'Lumia 720', 'image' => 'lumia_720.webp'],
                ['model' => 'Lumia 735', 'image' => 'lumia_735.webp'],
                ['model' => 'Lumia 925', 'image' => 'lumia_925.webp'],
                ['model' => 'Lumia 930', 'image' => 'lumia_930.webp'],
            ],
            'Wiko' => [
                ['model' => 'Barry', 'image' => 'barry.webp'],
                ['model' => 'Birdy', 'image' => 'birdy.webp'],
                ['model' => 'Bloom', 'image' => 'bloom.webp'],
                ['model' => 'Cink Peax 2', 'image' => 'cink_peax_2.webp'],
                ['model' => 'Darknight', 'image' => 'darknight.webp'],
                ['model' => 'Darkside', 'image' => 'darkside.webp'],
                ['model' => 'Getaway', 'image' => 'getaway.webp'],
                ['model' => 'Harry 2', 'image' => 'harry_2.webp'],
                ['model' => 'Lenny', 'image' => 'lenny.webp'],
                ['model' => 'Lenny 5', 'image' => 'lenny_5.webp'],
                ['model' => 'Rainbow 4G', 'image' => 'rainbow_4g.webp'],
                ['model' => 'Stairway', 'image' => 'stairway.webp'],
                ['model' => 'Sunset', 'image' => 'sunset.webp'],
                ['model' => 'Tommy 3', 'image' => 'tommy_3.webp'],
                ['model' => 'View 2', 'image' => 'view_2.webp'],
                ['model' => 'View 2 Go', 'image' => 'view_2_go.webp'],
                ['model' => 'View 2 Plus', 'image' => 'view_2_plus.webp'],
                ['model' => 'View 4', 'image' => 'view_4.webp'],
                ['model' => 'View 4 Lite', 'image' => 'view_4_lite.webp'],
                ['model' => 'View 5', 'image' => 'view_5.webp'],
                ['model' => 'View 5 Plus', 'image' => 'view_5_plus.webp'],
                ['model' => 'View Max', 'image' => 'view_max.webp'],
                ['model' => 'View3', 'image' => 'view3.webp'],
                ['model' => 'View3 Lite', 'image' => 'view3_lite.webp'],
                ['model' => 'View3 Pro', 'image' => 'view3_pro.webp'],
                ['model' => 'View4 Lite', 'image' => 'view4_lite.webp'],
                ['model' => 'Wax', 'image' => 'wax.webp'],
                ['model' => 'Wim Lite', 'image' => 'wim_lite.webp'],
                ['model' => 'Y51', 'image' => 'y51.webp'],
                ['model' => 'Y60', 'image' => 'y60.webp'],
                ['model' => 'Y61', 'image' => 'y61.webp'],
                ['model' => 'Y80', 'image' => 'y80.webp'],
                ['model' => 'Y81', 'image' => 'y81.webp'],
            ],
        ];

        foreach ($telephones as $nomMarque => $modeles) {
            $marque = $this->getReference($nomMarque);

            foreach ($modeles as $modeleData) {
                $telephone = new Telephone();
                $telephone->setNom($modeleData['model']);
                $telephone->setImage($modeleData['image']);
                $telephone->setMarque($marque);

                $manager->persist($telephone);
            }
        }

        $manager->flush();
    }
}
